In [3]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [22]:
tweets_train_DF = pd.read_csv("data/training_data.csv")

In [25]:
tweets_train_DF.head()

,id,id_str,screen_name,location,description,url,followers_count,friends_count,listed_count,created_at,favourites_count,verified,statuses_count,lang,status,default_profile,default_profile_image,has_extended_profile,name,bot
0,8.160000e+17,"""815745789754417152""","""HoustonPokeMap""","""Houston, TX""","""Rare and strong PokŽmon in Houston, TX. See m...","""https://t.co/dnWuDbFRkt""",1291,0,10,"""Mon Jan 02 02:25:26 +0000 2017""",0,False,78554,"""en""","{\r ""created_at"": ""Sun Mar 12 15:44:04 +0...",True,False,False,"""Houston PokŽ Alert""",1
1,4.843621e+09,4843621225,kernyeahx,"Templeville town, MD, USA",From late 2014 Socium Marketplace will make sh...,NaN,1,349,0,2/1/2016 7:37,38,False,31,en,NaN,True,False,False,Keri Nelson,1
2,4.303727e+09,4303727112,mattlieberisbot,NaN,"Inspired by the smart, funny folks at @replyal...",https://t.co/P1e1o0m4KC,1086,0,14,Fri Nov 20 18:53:22 +0000 2015,0,False,713,en,"{'retweeted': False, 'is_quote_status': False,...",True,False,False,Matt Lieber Is Bot,1
3,3.063139e+09,3063139353,sc_papers,NaN,NaN,NaN,33,0,8,2/25/2015 20:11,0,False,676,en,Construction of human anti-tetanus single-chai...,True,True,False,single cell papers,1
4,2.955142e+09,2955142070,lucarivera16,"Dublin, United States",Inspiring cooks everywhere since 1956.,NaN,11,745,0,1/1/2015 17:44,146,False,185,en,NaN,False,False,False,lucarivera16,1

In [26]:
tweetsDF.head()

,contributors,coordinates,created_at,entities,extended_entities,favorite_count,favorited,geo,id,id_str,...,quoted_status,quoted_status_id,quoted_status_id_str,retweet_count,retweeted,retweeted_status,source,text,truncated,user
0,NaN,None,2018-07-12 00:20:29,"{'hashtags': [], 'symbols': [], 'urls': [], 'u...",NaN,0,False,None,1017201997601222657,1017201997601222656,...,NaN,NaN,NaN,5,False,"{'contributors': None, 'coordinates': None, 'c...","<a href=""http://twitter.com"" rel=""nofollow"">Tw...",RT @HarvardChanSPH: Few U.S. medical schools e...,False,"{'contributors_enabled': False, 'created_at': ..."
1,NaN,None,2018-07-12 00:20:28,"{'hashtags': [], 'symbols': [], 'urls': [{'dis...",NaN,0,False,None,1017201994719813633,1017201994719813632,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://www.facebook.com/twitter"" rel=...","Harvard study finds that during heat waves, pe...",True,"{'contributors_enabled': False, 'created_at': ..."
2,NaN,None,2018-07-12 00:20:26,"{'hashtags': [], 'symbols': [], 'urls': [], 'u...",NaN,0,False,None,1017201985152520192,1017201985152520192,...,NaN,NaN,NaN,1,False,"{'contributors': None, 'coordinates': None, 'c...","<a href=""http://twitter.com/download/android"" ...",RT @CryptoSumer: @ShahanKhosh “We wanted to pa...,False,"{'contributors_enabled': False, 'created_at': ..."
3,NaN,None,2018-07-12 00:20:23,"{'hashtags': [], 'symbols': [], 'urls': [], 'u...",NaN,0,False,None,1017201973865734144,1017201973865734144,...,NaN,NaN,NaN,7,False,"{'contributors': None, 'coordinates': None, 'c...","<a href=""http://twitter.com/download/android"" ...",RT @HarvardHealth: Aspirin prevents heart atta...,False,"{'contributors_enabled': False, 'created_at': ..."
4,NaN,None,2018-07-12 00:20:22,"{'hashtags': [], 'symbols': [], 'urls': [], 'u...",NaN,0,False,None,1017201966542393344,1017201966542393344,...,NaN,NaN,NaN,2,False,"{'contributors': None, 'coordinates': None, 'c...","<a href=""http://twitter.com/download/iphone"" r...",RT @IvyLeagueFBMA: We’d like to take the time ...,False,"{'contributors_enabled': False, 'created_at': ..."